Layout/AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  Enabled: true
  EnforcedStyle: outdent

Naming/AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

Style/Alias:
  Description: 'Use alias_method instead of alias.'
  Enabled: false

Layout/AlignHash:
  Description: >-
    Align the elements of a hash literal if they span more than
    one line.
  Enabled: false

Layout/AlignParameters:
  Description: >-
    Align the parameters of a method call if they span more
    than one line.
  Enabled: false

Style/ArrayJoin:
  Description: 'Use Array#join instead of Array#*.'
  Enabled: false

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  Enabled: false

Naming/AsciiIdentifiers:
  Description: 'Use only ascii symbols in identifiers.'
  Enabled: false

Style/Attr:
  Description: 'Checks for uses of Module#attr.'
  Enabled: false

Style/BeginBlock:
  Description: 'Avoid the use of BEGIN blocks.'
  Enabled: false

Style/BlockComments:
  Description: 'Do not use block comments.'
  Enabled: false

Metrics/BlockNesting:
  Description: 'Avoid excessive block nesting'
  Enabled: false

Style/BlockDelimiters:
  Description: >-
    Avoid using {...} for multi-line blocks (multiline chaining is
    always ugly).
    Prefer {...} over do...end for single-line blocks.
  Enabled: false

Style/BracesAroundHashParameters:
  Description: 'Enforce braces style inside hash parameters.'
  Enabled: true

Style/CaseEquality:
  Description: 'Avoid explicit use of the case equality operator(===).'
  Enabled: false

Style/CharacterLiteral:
  Description: 'Checks for uses of character literals.'
  Enabled: false

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false

Style/CollectionMethods:
  Description: 'Preferred collection methods.'
  Enabled: false

Style/ColonMethodCall:
  Description: 'Do not use :: for method call.'
  Enabled: false

Style/CommentAnnotation:
  Description: >-
    Checks formatting of special comments
    (TODO, FIXME, OPTIMIZE, HACK, REVIEW).
  Enabled: false

Layout/CommentIndentation:
  Description: 'Indentation of comments.'
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Enabled: false

Style/PreferredHashMethods:
  Description: 'Checks for use of deprecated Hash methods.'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  Enabled: false

Style/DoubleNegation:
  Description: 'Checks for uses of double negation (!!).'
  Enabled: false

Style/EachWithObject:
  Description: 'Prefer `each_with_object` over `inject` or `reduce`.'
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Description: "Keep blank lines around access modifiers."
  Enabled: true

Layout/EmptyLines:
  Description: "Keeps track of empty lines around expression bodies."
  Enabled: false

Style/EmptyLiteral:
  Description: 'Prefer literals to Array.new/Hash.new/String.new.'
  Enabled: false

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

Style/EndBlock:
  Description: 'Avoid the use of END blocks.'
  Enabled: false

Style/EvenOdd:
  Description: 'Favor the use of Fixnum#even? && Fixnum#odd?'
  Enabled: false

Naming/FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: false

Lint/FlipFlop:
  Description: 'Checks for flip flops'
  Enabled: false

Style/FormatString:
  Description: 'Enforce the use of Kernel#sprintf, Kernel#format or String#%.'
  Enabled: false

Style/GlobalVars:
  Description: 'Do not introduce global variables.'
  Enabled: false

Style/GuardClause:
  Description: 'Check for conditionals that can be replaced with guard clauses'
  Enabled: false

Style/IfWithSemicolon:
  Description: 'Never use if x; .... Use the ternary operator instead.'
  Enabled: false

Layout/IndentFirstArrayElement:
  Description: >-
    Checks the indentation of the first element in an array
    literal.
  Enabled: false

Layout/IndentFirstHashElement:
  Description: 'Checks the indentation of the first key in a hash literal.'
  Enabled: false

Style/Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  Enabled: false

Style/LambdaCall:
  Description: 'Use lambda.call(...) instead of lambda.(...).'
  Enabled: false

Layout/LeadingCommentSpace:
  Description: 'Comments should start with a space.'
  Enabled: false

Style/LineEndConcatenation:
  Description: >-
    Use \ instead of + or << to concatenate two string literals at
    line end.
  Enabled: false

Style/MethodDefParentheses:
  Description: >-
    Checks if the method definitions have or don't have
    parentheses.
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Enabled: false

Style/ModuleFunction:
  Description: 'Checks for usage of `extend self` in modules.'
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/NegatedIf:
  Description: >-
    Favor unless over if for negative conditions
    (or control flow or).
  Enabled: false

Style/NegatedWhile:
  Description: 'Favor until over while for negative conditions.'
  Enabled: false

Style/Next:
  Description: 'Use `next` to skip iteration instead of a condition at the end.'
  Enabled: false

Style/NilComparison:
  Description: 'Prefer x.nil? to x == nil.'
  Enabled: false

Style/NonNilCheck:
  Description: 'Checks for redundant nil checks.'
  Enabled: false

Style/Not:
  Description: 'Use ! instead of not.'
  Enabled: false

Style/NumericLiterals:
  Description: >-
    Add underscores to large numeric literals to improve their
    readability.
  Enabled: false

Metrics/ParameterLists:
  Description: 'Avoid parameter lists longer than three or four parameters.'
  Enabled: false

Style/PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  Enabled: false

Style/PerlBackrefs:
  Description: 'Avoid Perl-style regex back references.'
  Enabled: false

Naming/PredicateName:
  Description: 'Check the names of predicate methods.'
  Enabled: false

Style/Proc:
  Description: 'Use proc instead of Proc.new.'
  Enabled: false

Style/RaiseArgs:
  Description: 'Checks the arguments passed to raise/fail.'
  Enabled: false

Style/RedundantBegin:
  Description: "Don't use begin blocks when they are not needed."
  Enabled: false

Style/RedundantException:
  Description: "Checks for an obsolete RuntimeException argument in raise/fail."
  Enabled: false

Style/RedundantSelf:
  Description: "Don't use self where it's not needed."
  Enabled: false

Style/RegexpLiteral:
  Description: >-
    Use %r for regular expressions matching more than
    `MaxSlashes` '/' characters.
    Use %r only for regular expressions matching more than
    `MaxSlashes` '/' character.
  Enabled: false

Style/RescueModifier:
  Description: 'Avoid using rescue in its modifier form.'
  Enabled: false

Style/SafeNavigation:
  Description: >-
    This cop transforms usages of a method call safeguarded by a check for the
    existance of the object to safe navigation (`&.`).
  Enabled: false

Style/SelfAssignment:
  Description: 'Checks for places where self-assignment shorthand should have been used.'
  Enabled: false

Style/Semicolon:
  Description: "Don't use semicolons to terminate expressions."
  Enabled: false

Style/SignalException:
  Description: 'Checks for proper usage of fail and raise.'
  Enabled: false

Style/SingleLineBlockParams:
  Description: 'Enforces the names of some block params.'
  Enabled: false

Style/SingleLineMethods:
  Description: 'Avoid single-line methods.'
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Description: >-
    Checks that exactly one space is used between a method name
    and the first argument for method calls without parentheses.
  Enabled: false

Layout/SpaceAroundKeyword:
  Description: 'Use spaces after if/elsif/unless/while/until/case/when.'
  Enabled: false

Layout/SpaceAfterNot:
  Description: Tracks redundant space after the ! operator.
  Enabled: false

Layout/SpaceBeforeComment:
  Description: >-
    Checks for missing space between code and a comment on the
    same line.
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Description: >-
    Checks that block braces have or don't have surrounding space.
    For blocks taking parameters, checks that the left brace has
    or doesn't have trailing space.
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  Enabled: true

Style/SpecialGlobalVars:
  Description: 'Avoid Perl-style global variables.'
  Enabled: false

Style/RedundantCapitalW:
  Description: 'Checks for %W when interpolation is not needed.'
  Enabled: false

Style/CommandLiteral:
  Description: 'Checks for %x when `` would do.'
  Enabled: false

Style/VariableInterpolation:
  Description: >-
    Don't interpolate global, instance and class variables
    directly in strings.
  Enabled: false

Style/WhenThen:
  Description: 'Use when x then ... for one-line cases.'
  Enabled: false

Style/WhileUntilDo:
  Description: 'Checks for redundant do after while or until.'
  Enabled: false

Style/WhileUntilModifier:
  Description: >-
    Favor modifier while/until usage when you have a
    single-line body.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
